name: Enforce Unit Tests

on:
  pull_request:
    branches:
      - main # or master
  push:
    branches:
      - main # or master

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.10.0
          enable-cache: true

      - name: Run prek
        run: |
          uv python install
          uv tool run prek --all-files --skip no-commit-to-branch

      - name: Run ruff check
        run: |
          uv run ruff format --check
          uv run ruff check

      - name: Run default unit tests
        run: |
          uv run pytest

      - name: Run type checking
        run: uv run pyright --stats

  check-backwards-compatibility:
    strategy:
      matrix:
        numpy_version: [==1.22.0, '']
        torch_version: [==1.11.0, '']
        python_version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        exclude:
          - numpy_version: ==1.22.0
            python_version: '3.12'
          - numpy_version: ==1.22.0
            python_version: '3.13'
          - numpy_version: ==1.22.0
            python_version: '3.14'
          - torch_version: ==1.11.0
            python_version: '3.14'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.10.0
          python-version: ${{ matrix.python_version }}
          enable-cache: true

      - name: Run tests
        run: |
          uv add --frozen 'torch${{ matrix.torch_version }}' 'numpy${{ matrix.numpy_version }}'
          uv run --frozen pytest

      - name: Run benchmarks
        run: |
          uv run --frozen benchmark.py
